sudo: required
dist: trusty

language: node_js

node_js:
#  - "6.3.0"
  - "4.1.2"

services:
  - mongodb

before_script:
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
    - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
    - sudo apt-get update
    - sudo apt-get install -y mongodb-org=2.6.6 mongodb-org-server=2.6.6 mongodb-org-shell=2.6.6 mongodb-org-mongos=2.6.6 mongodb-org-tools=2.6.6
    - sleep 15 #mongo may not respond immediatly
    - mongo --version
    - mongo chessMEAN --eval 'db.addUser("Billy", "pass");'

notifications: # set notification options
  email:
    recipients:
    - ivan.grabar15@gmail.com
# change is when the repo status goes from pass to fail or vice version
#	on_success: [always|never|change]
    on_success: change
#    on_failure: always
# Or we could just disable all email
#        email: false