sudo: required
dist: trusty

language: node_js

node_js:
  - "4.4.7"
#  - "node"

before_install:
#    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
#    - echo 'deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
#    - sudo apt-get update
#    - sudo apt-get install -y mongodb-org zip
#    - sleep 5 #mongo may not respond immediatly
    - mongo --version
    - sudo apt-get install -y zip

before_script:
    - npm start&

before_deploy:
    - zip app.zip * --exclude=*node_modules*
    - mkdir deploy
    - cp app.zip deploy/app.zip
#    - tar -zcvf chess.tar.gz deploy

deploy:
    skip_cleanup: true
    provider: s3
    #AWS Credentials need to be set in Travis
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    bucket: chess-bucket
#    upload-dir: chess
    region: eu-central-1
    local-dir: deploy
    on:
      all_branches: true
      
#    provider: codedeploy
#    access-key-id: $AWS_ACCESS_KEY
#    secret-access-key: $AWS_ACCESS_SECRET
#    bucket: chess-bucket
#    key: app.zip
#    application: chess
#    deployment_group: chessgroup
#    on:
#        all_branches: true
#    wait-until-deployed: true

notifications: # set notification options
  email:
    recipients:
    - ivan.grabar15@gmail.com
# change is when the repo status goes from pass to fail or vice version
#	on_success: [always|never|change]
    on_success: always
#    on_failure: always
