version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app

permissions:
- object: /
pattern: "**"
owner: ec2-user
group: ec2-user

hooks:
BeforeInstall:
- location: scripts/install_dependencies
timeout: 300
runas: ec2-user

ApplicationStart:
- location: scripts/start_server
timeout: 60
runas: ec2-user

