version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  Install::
      - location: /home/ec2-user/scripts/install_dependencies
        timeout: 120
        runas: ec2-user